# -*- coding: utf-8 -*-
"""Week3-Group1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6cuHPqvPlntEAUIfDA4O7E5VbfZvXjM
"""

print('我是經濟三甲張雅雯')

print("我是經濟一乙楊浥均")

print("我是經濟一乙林佳澐")

print("大家好我是經濟一乙劉子瑄")

print("學姊4廢物")

print("大家好我是經濟三甲的王緯華")

print("大家好我是經濟一乙鄭羽庭")

print("大家好我是經濟一乙的廖凰君")

