# -*- coding: utf-8 -*-
"""Week3-A106260073-張雅雯.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0qS4DlrQZRE2xAlfRymD00lt9PM65cN
"""

print('Hello World')